[package]
name = "catrap"
version = "0.1.0"
authors = ["alvarogonzalezsotillo@gmail.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html



[dependencies]

pathfinding = "4.3.1"

[dev-dependencies]
ntest = "0.7.5"
